"""INTERNAL EVALUATOR: InternVL2-26B pairwise reward.

The fine-tuned judge checkpoint and its reference-image corpus are internal and
are not among the seven public presets. ``INTERNVL_DUAL_CKPT`` must be set; the
adapter fails closed before loading the 26B base model.

Wraps a dual/pairwise InternVL judge (checkpoint supplied through ``INTERNVL_DUAL_CKPT``;
InternVL2-26B = InternViT-6B +
InternLM2-20B). It is shown TWO images for the same prompt — [generated, reference] — and asked
"is the first image better than the second? 是/否". The reward is **P(是/yes)** =
softmax(logit[是], logit[否])[是] at the final token, i.e. P(generated > reference).

Gradient mechanism is IDENTICAL to the pointwise scorer (src/internvl_t2i_scorer.py): a
MANUAL differentiable InternVL forward — `extract_feature(pixel_values)` → scatter ViT embeds
into the `<IMG_CONTEXT>` slots → `language_model(inputs_embeds=…)` → read the yes/no logits →
softmax. Gradient flows reward → yes/no logit → LM → vit_embeds → pixel_values → IMAGE. Model
frozen. So OPA can drive `autograd.grad(reward, generated_image)`.

Only the GENERATED image carries grad; the REFERENCE image is fixed data (detached). Maximizing
the reward pushes the generated image to beat its reference — a relative signal (unlike the
pointwise absolute P(score=5)).

MEMORY: 26B (~52 GB) + TWO images (2× ViT tiles) is heavier than pointwise and is intended for
dedicated reward GPUs rather than co-location per policy rank. This module is the reward core; the
deployment (2-GPU server / gradient bridge vs co-locate) wraps it.
"""

import os
from typing import Sequence

import torch
import torch.nn.functional as F
from transformers import AutoConfig, AutoModel, AutoTokenizer

from diffusionopsd.internvl_t2i_scorer import (  # reuse the pointwise machinery
    _force_nonreentrant_checkpoint,
    _load_finetuned_state_dict,
    _pad_to_square,
    _resolve_base_arch,
    IMAGENET_MEAN,
    IMAGENET_STD,
    IMG_CONTEXT_TOKEN,
    IMG_END_TOKEN,
    IMG_START_TOKEN,
    PROMPT_TEMPLATE,
)

DEFAULT_CHECKPOINT = os.environ.get(
    "INTERNVL_DUAL_CKPT", ""
)
DEFAULT_BASE_ARCH = os.environ.get(
    "INTERNVL_DUAL_BASE",
    "OpenGVLab/InternVL2-26B",
)
R_SIZE = 512   # dual __init__ default: resize each image to 512 before dynamic-preprocess to 448
TILE = 448

# --- pairwise prompt templates (verbatim from Internvl2_instruct_dual). template_type:
#   1 = *_aes_ti      ("if text-match comparable, then aesthetic")
#   2 = *_aes_ti_com  ("comprehensively evaluate text-match + aesthetic")  [default]
# Both ask about image1(=generated) vs image2(=reference); the two <image> slots are filled
# generated-first, reference-second.
_CN_AES_TI = (
    "\n你将扮演一位专业的图像质量评估师。你的任务是给定两张图片，这两张图片都是由同一个提示词生成，"
    "然后评估哪一张图片的生成质量更好，要考虑的因素包括“图文匹配”，“美感”。\n\n"
    "### 图文匹配：\n"
    "1. 物体的一致性：评估图片中的物体（例如人、动物、物体）与文字描述的匹配精准程度。需要考虑的因素包括数量、外观、行为和相对位置等方面。\n"
    "2. 文字的准确性：如果提示中要求生成某些文字，评估该文字是否被准确地生成。\n"
    "3. 风格一致性：如果提示中指定了一种特定的艺术或风格类型，需要考虑该图片与这种风格的契合程度。\n"
    "4. 环境一致性：评估背景以及场景是否符合提示词的要求。这包括检查现实世界中的地点或场景是否被准确呈现，不过一些风格上的调整是可以接受的。\n\n"
    "### 美感：\n"
    "1. 包括图像的构图，色彩，光影等。要特别注意，在写实场景中，着重考虑图像的自然程度，不能过度，例如要求脸色红润，生成的图片脸色红不能红的过度，不自然。\n\n"
    "### 评估方法：\n我们首先考虑图文匹配，如果图文匹配相当，再着重考虑美感的因素。\n\n"
    "现在根据如上的标准，给定两张图片：<image>\n<image>\n，这两张图片都是由如下提示词生成:“<prompt>”。"
    "你觉得第一张图是否比第二张图质量更好，请回答是或者否？注意，如果两张图片各有优劣，无法区分出哪张明显更好，则回答否。\n"
)
_CN_AES_TI_COM = _CN_AES_TI.replace(
    "### 评估方法：\n我们首先考虑图文匹配，如果图文匹配相当，再着重考虑美感的因素。",
    "### 评估方法：\n从“图文匹配”和“美感”两个角度综合评估。",
)
_EN_AES_TI = (
    "\nYou will act as a professional image quality evaluator. Your task is to be given two images, "
    "both of which are generated by the same prompt, and then evaluate which image has a better "
    "generation quality. The factors to be considered include \"text-image matching\" and \"aesthetic\".\n\n"
    "### Text-image matching:\n"
    "1. Object consistency: Evaluate the precise matching degree between the objects (such as people, "
    "animals, objects) in the image and the text description. Factors to be considered include quantity, "
    "appearance, behavior, and relative position, etc.\n"
    "2. Text accuracy: If the prompt requires the generation of certain texts, evaluate whether the text "
    "is accurately generated.\n"
    "3. Style consistency: When a specific art or style type is specified in the prompt, consider how well "
    "the image aligns with and captures the characteristics of that style.\n"
    "4. Environment Relevance: Assess whether the background and scene fit the prompt. This includes "
    "checking if real-world locations or scenes are accurately represented, though some stylistic "
    "adaptation is acceptable. \n\n"
    "### Aesthetic:\n"
    "1. This includes the composition, color, light and shadow of the image, etc. It should be noted that "
    "in realistic scenes, special attention should be paid to the naturalness of the image. For example, "
    "if a ruddy complexion is required, the complexion in the generated image should not be overly red "
    "and unnatural.\n\n"
    "Evaluation method:\nWe first consider text-image matching. If the text-image matching is comparable, "
    "then we focus on the factor of aesthetic.\n\n"
    "Now, according to the above criteria, given two images: <image>\n<image>\n, both of which are generated "
    "by the following prompt: “<prompt>”. Do you think the first image has better quality than the second "
    "image? Please answer yes or no. Note that if both images have their own advantages and disadvantages "
    "and it is impossible to distinguish which one is obviously better, then answer no.\n"
)
_EN_AES_TI_COM = _EN_AES_TI.replace(
    "Evaluation method:\nWe first consider text-image matching. If the text-image matching is comparable, "
    "then we focus on the factor of aesthetic.",
    "Evaluation method:\nComprehensively evaluate from the text-image matching and aesthetic.",
)
# template_type=0 (user-confirmed default): SHORT template with a <tags> criteria list built from
# tag_idxs (default '1' -> 图文匹配 / image-text matching). Verbatim from Internvl2_instruct_dual.
_CN_SHORT = ("<image>\n<image>\n这两幅图都是用这个文本生成的：<prompt> "
             "你觉得第一张图是否比第二张图好？请回答是还是否，评判标准包括：<tags>。")
_EN_SHORT = ("<image>\n<image>\nboth of these images were generated using this text: <prompt> "
             "Do you think the first image is better than the second one? Please answer with 'yes' or 'no'. "
             "The evaluation criteria include: <tags>.")
_CN_TAG2COND = {1: '图文匹配，', 2: '美感和图文匹配，', 3: '视觉效果，', 4: '结构，', 5: '色彩，', 6: '构图，'}
_EN_TAG2COND = {1: ' image-text matching,', 2: ' aesthetic and image-text matching,', 3: ' visual effect,',
                4: ' structure,', 5: ' colour,', 6: ' picture composition,'}
_TEMPLATES = {  # template_type -> (cn, en)
    0: (_CN_SHORT, _EN_SHORT),
    1: (_CN_AES_TI, _EN_AES_TI),
    2: (_CN_AES_TI_COM, _EN_AES_TI_COM),
}


def _has_chinese(s: str) -> bool:
    return any("一" <= c <= "鿿" for c in s)


class InternVLDualScorer(torch.nn.Module):
    """Differentiable pairwise reward P(generated > reference) from the InternVL2-26B dual judge."""

    def __init__(self, checkpoint_path: str = DEFAULT_CHECKPOINT, base_arch: str = DEFAULT_BASE_ARCH,
                 device: str = "cuda", dtype: torch.dtype = torch.bfloat16,
                 device_map_devices=None,  # GATED (INTERNVL_BRIDGE server): shard 26B over these GPUs
                 template_type: int = int(os.environ.get("INTERNVL_DUAL_TEMPLATE", "0")),
                 tag_idxs: str = os.environ.get("INTERNVL_DUAL_TAGS", "1")):
        super().__init__()
        if not checkpoint_path:
            raise RuntimeError(
                "INTERNVL_DUAL_CKPT is required. The paper's pairwise evaluator checkpoint is internal."
            )
        if not os.path.isfile(checkpoint_path):
            raise FileNotFoundError(f"INTERNVL_DUAL_CKPT does not exist: {checkpoint_path}")
        self.device = device
        self.dtype = dtype
        assert template_type in _TEMPLATES, f"template_type must be in {list(_TEMPLATES)}"
        self.template_type = template_type
        self.tag_idxs = [int(t) for t in str(tag_idxs).split(",") if t.strip()]  # only used by type 0

        base_arch = _resolve_base_arch(base_arch)
        use_flash = os.environ.get("INTERNVL_DUAL_FLASH", "0") == "1"
        config = AutoConfig.from_pretrained(base_arch, trust_remote_code=True)
        from transformers.modeling_utils import no_init_weights
        with no_init_weights():
            try:
                self.model = AutoModel.from_config(config, torch_dtype=dtype, use_flash_attn=use_flash,
                                                   trust_remote_code=True)
            except TypeError:
                self.model = AutoModel.from_config(config, torch_dtype=dtype, trust_remote_code=True)
        _load_finetuned_state_dict(self.model, checkpoint_path)
        if device_map_devices and len(device_map_devices) > 1:
            # GATED (INTERNVL_BRIDGE server): shard the frozen 26B across the reward GPUs, mirroring
            # the pointwise scorer's _dispatch_multi_gpu. IO modules (ViT, mlp1, LM token-embeddings,
            # final norm, LM head) are PINNED to `primary`, so _score_one's manual two-image forward
            # (pixel_values/input_ids/score-token buffers on primary, <IMG_CONTEXT> scatter on
            # primary, logits back on primary) needs ZERO changes; only decoder LAYERS split, and
            # accelerate's AlignDevicesHook moves the hidden state across GPUs with a differentiable
            # .to() so the reward->gen gradient flows across the device boundary exactly as on one GPU.
            from accelerate import dispatch_model
            from diffusionopsd.internvl_t2i_scorer import _build_internvl_device_map
            primary = int(str(device).split(":")[-1]) if isinstance(device, str) and ":" in str(device) else 0
            self.model = self.model.to(dtype=dtype)  # cast on CPU before dispatch (never a single .to(cuda))
            dmap = _build_internvl_device_map(self.model, primary, [int(d) for d in device_map_devices])
            self.model = dispatch_model(self.model, device_map=dmap).eval()
            print(f"[internvl_dual] sharded 26B across {list(device_map_devices)} (primary={primary}); "
                  f"{sum(v != primary for v in dmap.values())} modules off-primary", flush=True)
        else:
            self.model = self.model.to(device=device, dtype=dtype).eval()
        self.model.requires_grad_(False)
        if os.environ.get("INTERNVL_DUAL_GRADCKPT", "1") == "1":
            _force_nonreentrant_checkpoint()
            try:
                self.model.vision_model.gradient_checkpointing = True
                self.model.language_model.config.use_cache = False
                self.model.language_model.gradient_checkpointing = True
                self.model.language_model.model.gradient_checkpointing = True
            except Exception as exc:  # pragma: no cover
                print(f"[internvl_dual] grad-ckpt enable skipped: {exc}")
            self.model.train()

        self.tokenizer = AutoTokenizer.from_pretrained(base_arch, trust_remote_code=True, use_fast=False)
        self.img_context_token_id = self.tokenizer.convert_tokens_to_ids(IMG_CONTEXT_TOKEN)
        self.model.img_context_token_id = self.img_context_token_id
        self.num_image_token = int(self.model.num_image_token)  # 256 for 448 tile
        # yes/no token ids (last token of the encoding), matching the reference reader
        enc = lambda t: self.tokenizer(t, return_attention_mask=False, add_special_tokens=False)["input_ids"][-1]
        self.en_yes, self.en_no = enc("yes"), enc("no")
        self.cn_yes, self.cn_no = enc("是"), enc("否")

        self.register_buffer("_mean", torch.tensor(IMAGENET_MEAN).view(1, 3, 1, 1), persistent=False)
        self.register_buffer("_std", torch.tensor(IMAGENET_STD).view(1, 3, 1, 1), persistent=False)

    def _preprocess_one(self, image01: torch.Tensor) -> torch.Tensor:
        """[1,3,H,W] in [0,1] -> [1,3,448,448] model-dtype (pad->512->448->ImageNet-norm, single tile)."""
        x = image01.to(torch.float32)
        x = _pad_to_square(x, value=1.0)
        # reference path: resize to r_size=512 then dynamic_preprocess to a single 448 tile (square)
        x = F.interpolate(x, size=(R_SIZE, R_SIZE), mode="bicubic", align_corners=False, antialias=True)
        x = F.interpolate(x, size=(TILE, TILE), mode="bicubic", align_corners=False, antialias=True).clamp(0, 1)
        x = (x - self._mean.to(x)) / self._std.to(x)
        return x.to(self.dtype)

    def _build_prompt(self, prompt: str, chinese: bool) -> str:
        cn_t, en_t = _TEMPLATES[self.template_type]
        instruct = cn_t if chinese else en_t
        if self.template_type == 0:  # substitute the <tags> criteria list from tag_idxs
            tag2cond = _CN_TAG2COND if chinese else _EN_TAG2COND
            cat_tag = "".join(tag2cond[i] for i in self.tag_idxs)[:-1]  # drop trailing comma
            instruct = instruct.replace("<tags>", cat_tag)
        # quote the prompt like the reference (adds a trailing period + Chinese/English quotes)
        p = prompt
        if chinese:
            p = f"“{p}。”" if not p.endswith(("。", "，", "！", "？")) else f"“{p}”"
        else:
            p = f'"{p}."' if not p.endswith((".", ",", "!", "?")) else f'"{p}"'
        instruct = instruct.replace("<prompt>", p)
        cur = PROMPT_TEMPLATE.replace("<user_prompt>", instruct)
        image_tokens = IMG_START_TOKEN + IMG_CONTEXT_TOKEN * self.num_image_token + IMG_END_TOKEN
        # two <image> slots: first = generated, second = reference
        cur = cur.replace("<image>", image_tokens, 1).replace("<image>", image_tokens, 1)
        return cur

    def _score_one(self, gen01: torch.Tensor, ref01: torch.Tensor, prompt: str) -> torch.Tensor:
        chinese = _has_chinese(prompt)
        gen_px = self._preprocess_one(gen01)                 # grad flows here
        ref_px = self._preprocess_one(ref01).detach()        # reference is fixed data

        cur_prompt = self._build_prompt(prompt, chinese)
        enc = self.tokenizer(cur_prompt, return_tensors="pt")
        input_ids = enc["input_ids"].to(self.device)
        attention_mask = enc["attention_mask"].to(self.device)

        # extract_feature is per-image independent, so running gen (grad) and ref (no_grad) through the
        # ViT SEPARATELY and concatenating the embeds is numerically identical to a batched [gen,ref]
        # forward — but the ref half then holds NO backward activations. This ~halves the ViT autograd
        # memory of the OPA reward-gradient ascent, which otherwise died with CUDNN_STATUS_INTERNAL_ERROR
        # (memory pressure) on the 2-image dual reward. Order stays [generated, reference].
        gen_embeds = self.model.extract_feature(gen_px)
        with torch.no_grad():
            ref_embeds = self.model.extract_feature(ref_px)
        vit_embeds = torch.cat([gen_embeds, ref_embeds], dim=0)
        input_embeds = self.model.language_model.get_input_embeddings()(input_ids)
        B, N, C = input_embeds.shape
        flat = input_embeds.reshape(B * N, C).clone()
        selected = input_ids.reshape(B * N) == self.img_context_token_id
        assert int(selected.sum()) == vit_embeds.reshape(-1, C).shape[0], "IMG_CONTEXT/vit token mismatch"
        flat[selected] = vit_embeds.reshape(-1, C).to(flat.dtype)
        input_embeds = flat.reshape(B, N, C).to(self.dtype)

        out = self.model.language_model(inputs_embeds=input_embeds, attention_mask=attention_mask)
        logits = out.logits if hasattr(out, "logits") else out[0]
        last = logits[0, -1, :]                              # final-token logits
        yes_id, no_id = (self.cn_yes, self.cn_no) if chinese else (self.en_yes, self.en_no)
        pair = torch.stack([last[yes_id], last[no_id]]).float()
        return torch.softmax(pair, dim=-1)[0]                # P(yes) = P(generated > reference)

    def _scores(self, gen01: torch.Tensor, ref01: torch.Tensor, prompts: Sequence[str]) -> torch.Tensor:
        """Batched InternVL pairwise forward (right-pad + per-sample last-token read)
        so opa_mb>1 batches the 26B. One-time runtime parity check vs per-sample (fails loud)."""
        if isinstance(prompts, str):
            prompts = [prompts]
        prompts = list(prompts)
        if gen01.dim() == 3:
            gen01 = gen01.unsqueeze(0)
        if ref01.dim() == 3:
            ref01 = ref01.unsqueeze(0)
        gen01, ref01 = gen01.to(self.device), ref01.to(self.device)
        B = gen01.shape[0]
        if B == 1:
            return self._score_one(gen01, ref01, prompts[0]).reshape(1)
        if os.environ.get("INTERNVL_C_BATCHED", "0") != "1":
            # Batched _scores is disabled by default; see internvl_t2i_scorer for rationale.
            # (batched forward diverges > the 5e-3 parity bound on some 26B batches; the bridge server
            # always calls _scores with B>1). Exact per-sample loop; set INTERNVL_C_BATCHED=1 to debug.
            return torch.cat([self._score_one(gen01[i:i + 1], ref01[i:i + 1], prompts[i]).reshape(1) for i in range(B)])  # [B]
        out = self._scores_batched(gen01, ref01, prompts)
        if not getattr(self, "_batch_parity_ok", False):
            with torch.no_grad():
                ref = torch.stack([self._score_one(gen01[i:i + 1], ref01[i:i + 1], prompts[i]) for i in range(B)])
            if not (torch.isfinite(out).all() and torch.isfinite(ref).all()):
                raise RuntimeError("[internvl_dual C] non-finite reward in batched/per-sample parity check")
            md = (out.detach() - ref).abs().max().item()
            if not (md <= 5e-3):  # `not <=` also trips on NaN md
                raise RuntimeError(f"[internvl_dual C] batched vs per-sample reward max diff {md:.4g} > 5e-3")
            self._batch_parity_ok = True
        return out

    def _scores_batched(self, gen01: torch.Tensor, ref01: torch.Tensor, prompts: Sequence[str]) -> torch.Tensor:
        """One right-padded pairwise forward over the batch. Order per sample = [generated, reference];
        gen keeps grad, ref is no-grad (half the ViT autograd memory, matches _score_one)."""
        B = gen01.shape[0]
        gen_px = torch.cat([self._preprocess_one(gen01[i:i + 1]) for i in range(B)], dim=0)              # [B,3,448,448] grad
        ref_px = torch.cat([self._preprocess_one(ref01[i:i + 1]).detach() for i in range(B)], dim=0)     # [B,3,448,448] no-grad
        gen_embeds = self.model.extract_feature(gen_px)                 # [B,T,C] grad
        with torch.no_grad():
            ref_embeds = self.model.extract_feature(ref_px)            # [B,T,C] no-grad
        T, C = gen_embeds.shape[1], gen_embeds.shape[-1]
        vit = torch.stack([gen_embeds, ref_embeds], dim=1).reshape(B * 2 * T, C)  # [gen0,ref0,gen1,ref1,...]
        pad_id = self.tokenizer.pad_token_id
        if pad_id is None:
            pad_id = self.tokenizer.eos_token_id
        seqs, chinese = [], []
        for i in range(B):
            ch = _has_chinese(prompts[i]); chinese.append(ch)
            seqs.append(self.tokenizer(self._build_prompt(prompts[i], ch), return_tensors="pt")["input_ids"][0].to(self.device))
        Lmax = max(s.shape[0] for s in seqs)
        input_ids = torch.full((B, Lmax), pad_id, dtype=torch.long, device=self.device)
        attn = torch.zeros((B, Lmax), dtype=torch.long, device=self.device)
        lens = []
        for i, s in enumerate(seqs):
            L = s.shape[0]; lens.append(L); input_ids[i, :L] = s; attn[i, :L] = 1  # RIGHT-pad
        input_embeds = self.model.language_model.get_input_embeddings()(input_ids)  # [B,Lmax,C]
        selected = input_ids.reshape(-1) == self.img_context_token_id
        assert int(selected.sum().item()) == B * 2 * T, f"IMG_CONTEXT {int(selected.sum())} != {B * 2 * T}"
        flat = input_embeds.reshape(B * Lmax, C).clone()
        flat[selected] = vit.to(flat.dtype)                            # sample-order, [gen,ref] within sample
        input_embeds = flat.reshape(B, Lmax, C).to(self.dtype)
        out = self.model.language_model(inputs_embeds=input_embeds, attention_mask=attn)
        logits = out.logits if hasattr(out, "logits") else out[0]      # [B,Lmax,vocab]
        scores = []
        for i in range(B):
            last = logits[i, lens[i] - 1, :]                           # last REAL token (pre-pad)
            yes_id, no_id = (self.cn_yes, self.cn_no) if chinese[i] else (self.en_yes, self.en_no)
            scores.append(torch.softmax(torch.stack([last[yes_id], last[no_id]]).float(), dim=-1)[0])
        return torch.stack(scores)

    @torch.no_grad()
    def __call__(self, gen: torch.Tensor, ref: torch.Tensor, prompts: Sequence[str]) -> torch.Tensor:
        return self._scores(gen, ref, prompts).float()


_DUAL_CACHE: dict = {}


def get_internvl_dual_scorer(device: str = "cuda", checkpoint_path: str = DEFAULT_CHECKPOINT,
                             **kwargs) -> "InternVLDualScorer":
    """Process-level singleton (one 52 GB model/rank) — same rationale as the pointwise scorer."""
    key = (str(device), checkpoint_path)
    s = _DUAL_CACHE.get(key)
    if s is None:
        s = InternVLDualScorer(device=device, checkpoint_path=checkpoint_path, **kwargs)
        _DUAL_CACHE[key] = s
    return s
